# 适配 JDK 17 的 Maven 包发布工作流
name: Maven Package (JDK 17)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # 核心修改：将版本改为 17
          distribution: 'temurin'  # Temurin 是 Adoptium 提供的开源 JDK，兼容性好
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven  # 启用 Maven 缓存（JDK 17 构建可能依赖更多新库）

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MAVEN_OPTS: --add-opens java.base/java.lang=ALL-UNNAMED  # 解决 JDK 9+ 模块访问限制

      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_OPTS: --add-opens java.base/java.lang=ALL-UNNAMED  # 发布阶段也可能需要
    
